### ISSUE TITLE
SignKey.getRaw does not return Promise<String> 

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_app_nodejs#130]
When using the `beaker-plugin-safe-app` I came across an inconsistency between the documentation and a return value I received with `window.safeCryptoSignKey.getRaw`.

I believe `SignKey.getRaw` is the same method in this package, so I thought it would make sense to report it here.

It returns a `Promise<Object>` that resolves into an object with a `Uint8Array` under the `buffer` key:

    Object {
        buffer: Uint8Array(32)
    }

Instead of the [documented](http://docs.maidsafe.net/safe_app_nodejs/#SignKey#getRaw) `Promise<String>`.

**Comment by bochaco** [comment]
This is being fixed with https://github.com/maidsafe/safe_app_nodejs/pull/133 and https://github.com/maidsafe/beaker-plugin-safe-app/pull/61.
