### ISSUE TITLE
Unable to build, node 6.9.1, Debian - missing build-release

### ISSUE THREAD

**Issue by JPL1** [maidsafe/safe_app_nodejs#23]
Have installed Node 6.9.1 and Rust, downloaded and unzipped safe_app_nodejs-master.zip etc according to instructions, but when I run npm run build-release I get

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v6.9.1/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v6.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-release' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose stack Error: missing script: build-release
4 verbose stack     at run (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /home/user/Downloads/safe_app_nodejs-master
6 error Linux 4.4.38-11.pvops.qubes.x86_64
7 error argv "/home/user/.nvm/versions/node/v6.9.1/bin/node" "/home/user/.nvm/versions/node/v6.9.1/bin/npm" "run" "build-release"
8 error node v6.9.1
9 error npm  v3.10.8
10 error missing script: build-release
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
What am I doing wrong?

**Comment by frabrunelle** [comment]
@JPL1 I think the README needs to be updated. For now, you could try running `npm run build-system-uri-release` and `npm run build-safe-lib-release`. Let me know if that works for you 🙂

**Comment by JPL1** [comment]
No, that gave even more errors. I'm on Qubes by the way rather with Debian as a hosted VM, but usually that makes no difference.

0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v6.9.1/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v6.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-system-uri-release' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild-system-uri-release',
4 verbose run-script   'build-system-uri-release',
4 verbose run-script   'postbuild-system-uri-release' ]
5 info lifecycle safe-app@0.0.1~prebuild-system-uri-release: safe-app@0.0.1
6 silly lifecycle safe-app@0.0.1~prebuild-system-uri-release: no script for prebuild-system-uri-release, continuing
7 info lifecycle safe-app@0.0.1~build-system-uri-release: safe-app@0.0.1
8 verbose lifecycle safe-app@0.0.1~build-system-uri-release: unsafe-perm in lifecycle true
9 verbose lifecycle safe-app@0.0.1~build-system-uri-release: PATH: /home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/bin/node-gyp-bin:/home/user/Downloads/safe_app_nodejs-master/node_modules/.bin:/home/user/.nvm/versions/node/v6.9.1/bin:/home/user/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle safe-app@0.0.1~build-system-uri-release: CWD: /home/user/Downloads/safe_app_nodejs-master
11 silly lifecycle safe-app@0.0.1~build-system-uri-release: Args: [ '-c',
11 silly lifecycle   'cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native' ]
12 silly lifecycle safe-app@0.0.1~build-system-uri-release: Returned: code: 101  signal: null
13 info lifecycle safe-app@0.0.1~build-system-uri-release: Failed to exec build-system-uri-release script
14 verbose stack Error: safe-app@0.0.1 build-system-uri-release: `cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native`
14 verbose stack Exit status 101
14 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid safe-app@0.0.1
16 verbose cwd /home/user/Downloads/safe_app_nodejs-master
17 error Linux 4.4.38-11.pvops.qubes.x86_64
18 error argv "/home/user/.nvm/versions/node/v6.9.1/bin/node" "/home/user/.nvm/versions/node/v6.9.1/bin/npm" "run" "build-system-uri-release"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error safe-app@0.0.1 build-system-uri-release: `cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native`
22 error Exit status 101
23 error Failed at the safe-app@0.0.1 build-system-uri-release script 'cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the safe-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs safe-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls safe-app
23 error There is likely additional

**Comment by frabrunelle** [comment]
Which version of Rust are you using? I think we need to use 1.14.0 for now.

**Comment by JPL1** [comment]
I'm on 1.14.0. Probably something to do with Qubes. I'll try again on Ubuntu or something. Thanks for your help :)

**Comment by JPL1** [comment]
I've hit the same problem on Ubuntu. Here's what I did. 
Installed nodejs sudo apt-get install nodejs
nvm use 6.9.1
Installed Rust https://sh.rustup.rs -sSf | shcurl https://sh.rustup.rs -sSf | sh
Downloaded and unzipped Safe-app-node js from https://github.com/maidsafe/safe_app_nodejs/archive/master.zip
`cd  safe_app_nodejs_master`
run `npm run build-system-uri-release`

Then I get errors as per the log:
user@user-PC ~/Downloads/safe_app_nodejs-master $ cat /home/user/Downloads/safe_app_nodejs-master/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v6.9.1/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v6.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-system-uri-release' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prebuild-system-uri-release',
4 verbose run-script   'build-system-uri-release',
4 verbose run-script   'postbuild-system-uri-release' ]
5 info lifecycle safe-app@0.0.1~prebuild-system-uri-release: safe-app@0.0.1
6 silly lifecycle safe-app@0.0.1~prebuild-system-uri-release: no script for prebuild-system-uri-release, continuing
7 info lifecycle safe-app@0.0.1~build-system-uri-release: safe-app@0.0.1
8 verbose lifecycle safe-app@0.0.1~build-system-uri-release: unsafe-perm in lifecycle true
9 verbose lifecycle safe-app@0.0.1~build-system-uri-release: PATH: /home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/bin/node-gyp-bin:/home/user/Downloads/safe_app_nodejs-master/node_modules/.bin:/home/user/.nvm/versions/node/v6.9.1/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle safe-app@0.0.1~build-system-uri-release: CWD: /home/user/Downloads/safe_app_nodejs-master
11 silly lifecycle safe-app@0.0.1~build-system-uri-release: Args: [ '-c',
11 silly lifecycle   'cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native' ]
12 info lifecycle safe-app@0.0.1~build-system-uri-release: Failed to exec build-system-uri-release script
13 verbose stack Error: safe-app@0.0.1 build-system-uri-release: `cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid safe-app@0.0.1
15 verbose cwd /home/user/Downloads/safe_app_nodejs-master
16 error Linux 4.4.0-53-generic
17 error argv "/home/user/.nvm/versions/node/v6.9.1/bin/node" "/home/user/.nvm/versions/node/v6.9.1/bin/npm" "run" "build-system-uri-release"
18 error node v6.9.1
19 error npm  v3.10.8
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error safe-app@0.0.1 build-system-uri-release: `cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native`
24 error spawn ENOENT
25 error Failed at the safe-app@0.0.1 build-system-uri-release script 'cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the safe-app package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     cd system_uri && cargo build --release && cd ../ && cp -f system_uri/target/release/*system_uri* ./src/native
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs safe-app
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls safe-app
25 error There is likely addi

**Comment by krishnaIndia** [comment]
Can you please check the Rust version(`rustc --version`) on your ubuntu? The rustup installs the latest version(1.15.*) I hope.

**Comment by JPL1** [comment]
Yes, I reinstalled it using rustup to make sure - it's the latest version 1.15.0 (I'm on another computer at the moment)

**Comment by frabrunelle** [comment]
I just tried on Ubuntu and I get an error when trying to build the release builds (`build-system-uri-release` works fine, but not `npm run build-safe-lib-release`). I think we don't support release builds at the moment.

I would recommend building the debug builds for now (`npm run build-libs`). This should automatically happen when you run `npm install` (because of the `prepublish` script).

Also, make sure to use Rust 1.14.0 (I think there is a bug in 1.15.0 with workspaces).

Try this and let me know if it works:

```
git clone https://github.com/maidsafe/safe_app_nodejs.git
git submodule init && git submodule update
npm install
```

**Comment by JPL1** [comment]
Yes that worked. Thanks
