### ISSUE TITLE
Fix all lint and test errors reported in the dev branch

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_app_nodejs#264]

**Comment by joshuef** [comment]
Started in a branch: https://github.com/joshuef/safe_app_nodejs/commit/96ef7bab35cefa78946a2e25d72fe30f9d2dc165

**Comment by joshuef** [comment]
the remaining lint errors are this: https://eslint.org/docs/rules/class-methods-use-this

which I'm not sure what the best way is to handle... we could do as they suggest and make everything static. I suppose. Or simply ignore... thoughts, @bochaco ?

**Comment by bochaco** [comment]
@joshuef , as agreed let's fix the lint issue in a separate PR and again issue #264

**Comment by joshuef** [comment]
Got this down to one test failing (on osx). 

I'm not really sure what this test is, nor why having a log file constitutes a failure at all...

```
  1) Sandbox should return undefined value if log option is true, however app logging is not initialised:
     AssertionError: expected '/Users/josh/.nvm/versions/node/v8.11.2/bin/NodeJS_Test.MaidSafe.net_Ltd.log' to be undefined
```

**Comment by joshuef** [comment]
(https://github.com/maidsafe/safe_app_nodejs/commit/aaad47736f98217e2802c3480e7a06cb22b3a827 contains all tests passing but this one, for ref).

**Comment by bochaco** [comment]
I'm looking at the error in the webId test you mentioned @hunterlester, so I propose @joshuef you can mark that test to skip in your PR and I'll fix it as part of my PR for issue #261.

**Comment by joshuef** [comment]
Fixed by https://github.com/maidsafe/safe_app_nodejs/commit/405b42bd60f4b063277e9d64913f16e5abc0cb90 

Which I seem to have accidentally pushed to `dev` branch here. Apologies.

**Comment by joshuef** [comment]
I'm going to mark this as closed as it's in the `dev` branch (and was a simple ignore a test tweak).

We can reopen if required. (@bochaco FYI)
