### ISSUE TITLE
Install dev and prod libs by default

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_app_nodejs#277]
When `yarn`ing, you're a dev. 

Having to remember to add `NODE_ENV=dev` on install is a PITA.

I propose we download both by default and leave it up to the app to exclude the dir they don't want in their build...

**Comment by krishnaIndia** [comment]
Do we cache them for CI? If not could be an enhancement for the [deps_downloader](https://github.com/maidsafe/deps_downloader)?

**Comment by joshuef** [comment]
Hmm, they're dlded into node_modules, so should be cached with the CI policy on _that_. I think.

Not 100% sure though, good Q!

**Comment by bochaco** [comment]
@joshuef , perhaps as you said by default both are downloaded, but keep the option to download only the dev or prod with NODE_ENV=dev/prod? which will be helpful for example in our/any CI, so it can be used for efficiency by whoever needs such a thing, as well as for simplifying the job/scripts needed to package apps as they can optionally set to prod when they are installing to package it?
