### ISSUE TITLE
getContainer('_public') fails with "Requested data not found"

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe_app_nodejs#279]
On Linux Ubuntu 18 using safenetwork-fuse CLI app I'm developing:

Immediately after auth I'm calling `safeApp.auth.getContainer('_public')` and it is failing with:  
`-103: Core error: Routing client error -> Requested data not found`

This code was working up until about 20 hours ago and while making unrelated changes this error suddenly started happening. It may well be my code, but given the auth code has been working fine during development for weeks (or more) I don't know how! The error is strangely identical to the one which flagged up problems with the Alpha 2 network recently, although [David Geddes reports](https://forum.safedev.org/t/any-probs-with-apha-2-core-error-routing-client-error-requested-data-not-found/1951/7?u=happybeing) all currently seems fine (on the rebooted network).

I've checked in the following repos which will allow it to be tested, both tagged with `wip-getcontainerbug` and both on the `development` branch. The first link is a nodejs CLI app (a SAFE FUSE mount) built *without electron* and I'm using `npm link safenetworkjs` to access the second, which is a library I'm making to encapsulate the SAFE API.

   https://github.com/theWebalyst/safenetwork-fuse/tree/development
   https://github.com/theWebalyst/safenetworkjs/tree/development

I'm debugging this with the live net, using Peruse 0.6 for auth only. So to test this:

1. clone the repos, check out tag `wip-getcontainerbug` in each
2. in safenetworkjs: `npm link`
3. in safenetwork-fuse: `npm link safenetworkjs`
4. start Peruse Dev 0.6 with flag '--live' and login to an account
5. start Chromium or Chrome and navigate to the debugger URI: chrome://inspect/#devices
6. in safenetwork-fuse: `DEBUG=safe-fuse*,safenetworkjs* NODE_ENV=dev node --inspect-brk bin.js`
7. open the Chrome debugger by clicking 'Open dedicated DevTools for Node'
8. debugger should open in bin.js so set breakpoints as needed around the line with `safeJsApi.auth.getContainer('_public')` 
9. Hit F8 to run, Peruse should request auth for 'SAFE Network FUSE' and when you accept you'll see the error at the `getContainer()` call in `safenetwork-fuse/bin.js`

**Comment by bochaco** [comment]
@theWebalyst , I was able to reproduce it, and it’s just that you are getting an authorisation URI from Peruse against the live (alpha2) network since you are running it with `--live`, but you are then actually trying to connect to mock network since you are running safenetwork-fuse with `NODE_ENV=dev` in this command: `DEBUG=safe-fuse*,safenetworkjs* NODE_ENV=dev node --inspect-brk bin.js`

I just tried removing `NODE_ENV=dev` from that command and the error is gone. Then I can see sometimes I get the `Utf8("invalid utf-8: corrupt contents")` error but that’s being solved as you know, so just after retrying I don’t see any other error but not sure what happens then, it seems the debugger looses the connection.

**Comment by theWebalyst** [comment]
Ah you are a life saver Gabriel, thanks so much. I’ve been wracking my brain trying to think what could have changed. I can see how that happened: usually I grab that command from the shell history but after a reboot I will have copied and pasted it from my notes.

Phew and yipeee! I can get back to work. Thanks again. 😄

Sometimes you need a second pair of eyes - it might have taken me days to spot this. Which made me think.

I could certainly do this again, so will make notes to help me spot it, and others developing stand alone (desktop) apps will likely do this too. So I wonder if it would be worth detecting and flagging it - auth URI includes a flag (mock) that can be checked in the client library when used?

I’m guessing we haven’t seen this before because NODE_ENV was the only way to select mock/live, but with CLI also an option it will be easy for desktop app devs to do this.

What do you think - worth me creating a feature request?

**Comment by Viv-Rajkumar** [comment]
> So I wonder if it would be worth detecting and flagging it

You mean apart from [safe_core::is_mock_build](https://docs.rs/safe_core/0.31.0/safe_core/ffi/fn.is_mock_build.html) which I'm assuming is exposed via [nodejs:: isMockBuild](http://docs.maidsafe.net/safe_app_nodejs/#safeappismockbuild)?

**Comment by theWebalyst** [comment]
> You mean apart from safe_core::is_mock_build which I'm assuming is exposed via nodejs::isMockBuild?

I don't think so - I was thinking that if I get an auth URI from the browser, it wraps a flag to indicate mock/live. So that when the app uses the URI, the SAFE library can validate that it is dev for mock net, or prod for live net, and complain if not.

**Comment by bochaco** [comment]
That could be done if agreed but it'll need to go in the [safe_client_libs](https://github.com/maidsafe/safe_client_libs)

**Comment by bochaco** [comment]
The safe_cllient_libs team has created an item to implement such an enhancement/feature: https://maidsafe.atlassian.net/browse/MAID-3148
