### ISSUE TITLE
Fetch RDF from encrypted public names container

### ISSUE THREAD

**Issue by b-zee** [maidsafe/safe_app_nodejs#283]
Version: dev

This snippet:
```
const cont = await app.auth.getContainer('_publicNames');

const rdf = cont.emulateAs('RDF');
await rdf.nowOrWhenFetched();
```

Gives:
```
1023: No ID has been found in the RDF graph.
at module.exports (node_modules\@maidsafe\safe-node-app\src\native\_error.js:32:10)
at RDF.nowOrWhenFetched (node_modules\@maidsafe\safe-node-app\src\api\emulations\rdf.js:100:13)
at <anonymous>
```

<hr>

This is when the public names container is already populated by creating a few WebIDs by the WebID emulation helper.

**Comment by bochaco** [comment]
Now that we are merging the RDF experimental APIs onto `master` branch behind the `--enableExperimentalApis` flag, we can consider fixing this with higher priority.
