### ISSUE TITLE
Passing zero to `nfs.update(...)` multiple times without error.

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_app_nodejs#291]
https://forum.safedev.org/t/implementing-nfs-api-rename/2109/13

I'm able to pass `0` as the version when updating a file multiple times without error.
`nfs.update(fileName, file, 0, userMetadata)`
Is this expected behavior?

**Comment by bochaco** [comment]
@hunterlester as per further comments in that thread it seems it's expected and it's a feature provided by the underlying safe_app lib, although I'd say we are missing a constant for that specific value, similar to the constants we have for other functions, e.g. `USER_ANYONE`, `NFS_FILE_END`, etc.
