### ISSUE TITLE
Upgrade native safe_app lib to v0.9.0

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_app_nodejs#299]
Adapt the APIs as required to upgrade safe_app lib to v0.9.0.

**Comment by hunterlester** [comment]
- Possible includes https://github.com/maidsafe/safe_client_libs/pull/691
- https://github.com/maidsafe/safe_app_nodejs/pull/293 open

**Comment by hunterlester** [comment]
Also reference https://github.com/maidsafe/safe_client_libs/pull/691
