### ISSUE TITLE
Expose operations that decodes XOR-URL and returns 32-byte Buffer

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_app_nodejs#318]
Say I have `safe://hyfktcerbwpctjz6ws8468hncw1ddpzrz65z3mapzx9wr413r7gj3w6yt5y:15001`, I'd like to use it be be able to call `newPublic` to obtain an interface.

**Comment by bochaco** [comment]
@hunterlester , you can actually do that already with the `fetch` function, you just invoke it with that XOR-URL.
