### ISSUE TITLE
rdf.nowOrWhenFetched returning `No ID has been found in the RDF graph`

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe_app_nodejs#319]
Having stored RDF data in an underlying MutableData using `rdf.commit`, I'm unable to fetch it with `norOrWhenFetched`, receiving `1027: No ID has been found in the RDF graph.`.

Here is the data which is stored, which definitely has an `@id` property.
```
{
    "@id": "http://dbpedia.org/resource/Pluto",
    "http://dbpedia.org/ontology/discovered": [{
        "@value": "1930-02-18T08:00:00.000Z",
        "@type": "http://www.w3.org/2001/XMLSchema#dateTime"
    }],
    "http://dbpedia.org/property/atmosphereComposition": [{
        "@id": "http://dbpedia.org/resource/Methane"
    }],
    "http://www.w3.org/2000/01/this-schema#type": [{
        "@id": "http://dbpedia.org/resource/Dwarf_planet"
    }]
}
```

Can be easily reproduced with API playground using [this branch](https://github.com/hunterlester/safe_examples/tree/XorUrl).

**Comment by hunterlester** [comment]
Issue due to user error.
When I set ID I was only passing a string instead of passing a node resource.
Closing.

**Comment by b-zee** [comment]
Perhaps setting the ID should be done through a `setId` method that checks the argument/string passed?

**Comment by bochaco** [comment]
I think there is room for enhancement in this regard, me as a user/dev would love to not need to set the ID when calling `nowOrWhenFetched`, I would love if the function can do it itself, which is doing it in some cases IIRC, but I think the are issues with the serialisation of the RDF which we seem to not be covering all the different cases. Anyway, this is just how I view it, and the following comment in the code is related to this issue: https://github.com/maidsafe/safe_app_nodejs/blob/master/src/api/emulations/rdf.js#L106
